### PR TITLE
UI updates

### PR DESCRIPTION
**Pull request by brianannis**
Thank you for your submission to the FreeNAS community plugins repository!

Please ensure the following guidelines are met when submitting a new Plugin.

- [x] Add the entry to INDEX in alphabetical order
- [x] Includes a new icon in the ./icon/ directory
- [x] Ensure the submitted icon file is a valid PNG that is 128x128 in size

- Updated logo remove white corners
- Renamed plugin to "Resilio Sync" in TrueNAS UI to match previous IX managed plugin name

### CODE REVIEW

**Review by sonicaj — COMMENTED** [review]
Can you please let me know why we should default to dhcp instead of nat ?

**Comment by fahadshery** [comment]
> Can you please let me know why we should default to dhcp instead of nat ?

Because I being a user use DHCP and get my router to offer static IP. This is way more manageable and error free in my experience. Therefore, I prefer DHCP and get my router to manage IP addresses for each jail

**Comment by sonicaj** [comment]
@fahadshery can you please let me know what errors you are experiencing with NAT ?

**Comment by brianannis** [comment]
> Can you please let me know why we should default to dhcp instead of nat ?

This was done to match the behavior of previous ix maintained plugin, happy to leave it as NAT.

**Comment by sonicaj** [comment]
@fahadshery @brianannis we did not have NAT before and we defaulted to dhcp. With NAT, we would like plugins to use NAT wherever possible by default unless of course their are technical reasons. Can we please update the PR then to remove dhcp change if there are no other concerns with NAT ? Thanks

**Comment by kmoore134** [comment]
This has been sitting a long while... Please re-open if you want to re-submit.

**Pull request closed without merging**
