### PR TITLE
Add zrepl plugin

### PR DESCRIPTION
**Pull request by johnramsden**
## Summary

[zrepl](https://zrepl.github.io/) is zfs replication software.

## Tests

Tested the plug-in via:

```
iocage fetch -P /tmp/zrepl.json --name zrepl-test jail_zfs_dataset="zrepl"
```

## Questions

Regarding setup tasks. I couldn't find a way to run commands on the main system, I don't know if this is possible. Is there a way to have a user specify a dataset they want delegated, and optionally created? For now I have left a [message](https://github.com/johnramsden/iocage-plugin-zrepl/blob/9aa1899a42797e3070a6e3f63ab3b3c99db73dfc/post_install.sh#L12-L29) in the `post_install.sh` stating:

> A ZFS dataset must be delegated into the zrepl jail. Create a dataset on the
> host if one was not delegated during jail creation, stop the plugin jail,
> and set the following iocage property:
> 
>     jail_zfs_dataset=<delegated dataset>
> 
> The "\<delegated dataset\>" should not contain the pool name.
> 
>

### CODE REVIEW

**Comment by johnramsden** [comment]
Resized icon.

**Comment by johnramsden** [comment]
@kmoore134 thanks!

I'm trying to test the plugin on my FreeNAS, is there a way to specify to use this index? I couldn't find anything in the man pages.

Right now I'm using the following and it cannot find the plugin:

    iocage fetch -P zrepl --name zrepl-test jail_zfs_dataset=zrepl boot=on --branch master

I get:

    /mnt/tank/iocage/.plugins/github_com_freenas_iocage-ix-plugins_git/zrepl.json was not found!

**Comment by kmoore134** [comment]
I normally test it by grabbing the .json file locally and running:

iocage fetch -P ./zrepl.json

You can also drop that file into /mnt/tank/iocage/.plugins/github_com_freenas_iocage-ix-plugins/ manually to fake it out ;)

Kris Moore
Vice President of Engineering
iXsystems, Inc
Phone: (408) 943-4100
The Groundbreaking TrueNAS M-Series -
Enterprise Storage & Servers Driven By Open Source

**Comment by johnramsden** [comment]
@kmoore134 So via the webui it will show up in community plugins, but not in the cli?

**Comment by kmoore134** [comment]
It will show up in both, but not until I backport it to 11.3-RELEASE branch. Will do that soon :)

Kris Moore
Vice President of Engineering
iXsystems, Inc
Phone: (408) 943-4100
The Groundbreaking TrueNAS M-Series -
Enterprise Storage & Servers Driven By Open Source

**Pull request merged**
