### PR TITLE
Remove unmaintained plugins

### PR DESCRIPTION
**Pull request by tprelog**
I have moved over to TrueNAS SCALE now. It's no longer feasible for me to continue maintaining these plugins.

- gogs
- mosquitto
- tasmoadmin
- nodered

### CODE REVIEW

**Review by sonicaj — APPROVED** [review]
Thank you @tprelog!

**Comment by nirvdrum** [comment]
Can we please avoid deleting files like this in the future? The gogs plugin was working fine. Deleting it from the index breaks the ability to upgrade the jail at all because the manifest can no longer be found. It's a community index, so if someone no longer wants to maintain a plugin, it's fine to leave that to someone else. Or just leave it. Many of these plugins don't really need any maintenance other than base release version.

**Comment by nirvdrum** [comment]
In case anyone else runs into this, I finally figured out a workaround.

Previously, I was seeing:

```
% sudo iocage upgrade --release 13.1-RELEASE gogs
Snapshotting gogs...
Snapshot already exists
Updating plugin INDEX...
Cloning git repository
A plugin manifest matching gogs could not be found!
```

The error message wasn't entirely helpful since I do have the plugin files as it was already installed. Eventually I came across a [thread about the plugin deletion](https://www.truenas.com/community/threads/ixsystems-when-are-you-going-to-stop-pretending-that-core-has-usable-plugins.104355/page-2#post-728207). I thought the easiest solution would be to locally roll back the git version:

```
% cd /mnt/<pool_name>/iocage/.plugins/github_com_ix-plugin-hub_iocage-plugin-index_git
% sudo git checkout fad2dcf
% sudo iocage upgrade --release 13.1-RELEASE gogs
```

Unfortunately, that fails because iocage always attempts to change the branch to the latest. Looking at the iocage log (_/var/log/iocage.log_) I saw the following entries:

```
2023/05/24 02:26:52 (INFO) Updating plugin INDEX...
2023/05/24 02:26:52 (DEBUG) Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=/mnt/<pool_name>/iocage/.plugins/github_com_ix-plugin-hub_iocage-plugin-index_git, universal_newlines=False, shell=None, istream=None)
2023/05/24 02:26:52 (DEBUG) Popen(['git', 'checkout', '13.1-RELEASE'], cwd=/mnt/<pool_name>/iocage/.plugins/github_com_ix-plugin-hub_iocage-plugin-index_git, universal_newlines=False, shell=None, istream=None)
```

I couldn't find a way to disable that. I did try to `git reset fad2dcf` on the branch to trick iocage into running the commit I wanted, but that resulted iocage deleting the entire directory.

My final solution was to make a local modification to the git directory restoring the [_gogs.json_ file](https://raw.githubusercontent.com/ix-plugin-hub/iocage-plugin-index/fad2dcf619736473be85c1d15e13f147478f302f/gogs.json):


```
% wget https://raw.githubusercontent.com/ix-plugin-hub/iocage-plugin-index/fad2dcf619736473be85c1d15e13f147478f302f/gogs.json -O /tmp/gogs.json
% sudo mv /tmp/gogs.json /mnt/<pool_name>/iocage/.plugins/github_com_ix-plugin-hub_iocage-plugin-index_git/
% sudo iocage upgrade --release 13.1-RELEASE gogs
```

Fortunately, iocage doesn't perform a `git clean` so the local file is retained and I could then complete the upgrade.

I don't expect this will work in the long-term, but it could help you out if you're stuck trying to upgrade the FreeBSD base for a removed plugin.

**Comment by tprelog** [comment]
> Can we please avoid deleting files like this in the future? The gogs plugin was working fine.

Sorry about that. As the previous maintainer of the gog plugin, the issue is that I'm no longer using TrueNAS Core or any IOCAGE jails. It's not feasible to continue maintaining plugins on a platform I no longer use. You could always fork the artifact repo and adjust the plugin manifest to point at your fork. You can also submit a PR here to have Gogs re-added using your fork.

A better option might be moving your Gogs installation to a regular jail. IX-Systems is planning to depreciate plugins by 2025. More on that can be found in the following links.

https://www.truenas.com/community/threads/ixsystems-when-are-you-going-to-stop-pretending-that-core-has-usable-plugins.104355/

https://www.truenas.com/blog/the-future-of-truenas-plugins-is-apps/

**Pull request merged**
