### PR TITLE
update homeassistant for TrueNAS Core

### PR DESCRIPTION
**Pull request by tprelog**
Home Assistant _Core_ on TrueNAS _Core_...

getting to the _Core_...
it's all about the _Core_...
this release will be hard _Core_..

:rofl:  :roll_eyes:

### CODE REVIEW

**Comment by tprelog** [comment]
Is there any additional information I can provide to help get this merged to the 12.1-RELEASE branch. The Home Assistant Core plugin will fail to install on TrueNAS Core until this is merged

**Comment by tprelog** [comment]
Thank you sir, I'll try to keep these manifest changes to a minimum in the future.

The back and forth with `openssl` in the 11.3-RELEASE provided a good learning experience. I won't be so quick to make a change like that next time

**Comment by sonicaj** [comment]
Thank you for your contribution

**Comment by sonicaj** [comment]
Can you please make a PR against 12.1-RELEASE branch as well with the same diff ?

**Pull request merged**
