### PR TITLE
Couchpotato removal

### PR DESCRIPTION
**Pull request by aidik**
The Couchpotato template is not working anymore mostly due to the Couchpotato being deprecated for the need for Python 2.7 which already reached EoL.

freenas/iocage-plugin-couchpotato#1

### CODE REVIEW

**Review by sonicaj — CHANGES_REQUESTED** [review]
Please delete `couchpotato.json` as well, we are not using it anymore.

**Comment by sonicaj** [comment]
Also `icon/couchpotato.png`

**Comment by aidik** [comment]
@sonicaj the files are removed as well.

**Review by sonicaj — APPROVED** [review]
Thank you

**Pull request merged**
