### PR TITLE
Logitechmediaserver needs custom fork of faad2 ( issue #258 )

### PR DESCRIPTION
**Pull request by titou386**
Thank you for your submission to the FreeNAS community plugins repository!

Please ensure the following guidelines are met when submitting a new Plugin.

1. Add the entry to INDEX in alphabetical order
2. Includes a new icon in the ./icon/ directory
3. Ensure the submitted icon file is a valid PNG that is 128x128 in size
4. Add new plugin cirrus task

### CODE REVIEW

**Review by sonicaj — APPROVED** [review]
Thank you @titou386 for your contribution. To confirm, `faad2` is going to be included in the plugin repo by https://github.com/titou386/iocage-plugin-logitechmediaserver/issues/3 ?

**Comment by titou386** [comment]
Yes, but I had to revert to the previous commit, the install fail because i have some conflicts with the package files and my compiled files of faad2.
Thank you.

**Comment by sonicaj** [comment]
Thank you for clarifying @titou386, please let me know when you think i should merge this ( i guess that would be once the issues have been resolved in the plugin repo ) :)

**Comment by titou386** [comment]
You can merge.
When the merge will be done in ix-plugin-hub, i will push `faad2` binaries in my repository as soon as possible.
( Logitech media server can work without `faad2`, but there will be no transcoding for `MPEG-4`, `AAC` and `Apple Lossless` file formats for old players )
Thank you.

My tests on my local machine with custom faad2 :
```
root@LMS2:/media/Music/Test/m4a/Debussy Piano Works Volume 1_ Suite Berg # faad 01\ Debussy_\ Suite\ Bergamasque\ -\ Prel.m4a 
 *********** Ahead Software MPEG-4 AAC Decoder V2.7 ******************

 Patched for Squeezebox Server:
 * ALAC decoder integrated
 * Seeking support with -j and -e switches
 * STDIN support
 * utgg win32 STDOUT patch
 * Source at https://github.com/ralph-irving/faad2

 Build: Aug 13 2021
 Copyright 2002-2004: Ahead Software AG
 http://www.audiocoding.com
 Floating point version

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License.

 **************************************************************************

file info:

277.293 secs, 2 ch, samplerate=44100, timescale=44100
...
```
On-the-fly transcoding with Logitech media sever: ( faad: Apple Lossless -- > WAV | logitechmediaserver pipe | sox: WAV --> FLAC )
```
root@LMS2:~ # ps awwx
  PID STAT    TIME  SL  RE PAGEIN    VSZ    RSS LIM TSIZ %CPU %MEM COMMAND
...
39948  -  SJ   0:00.52 /usr/local/bin/faad -q -w -f 1 /media/Music/Test/m4a/Debussy Piano Works Volume 1_ Suite Berg/09 Debussy_ Arabesque #1.m4a
39949  -  SJ   0:00.22 /usr/local/bin/sox -q -t wav - -t flac -C 0 -
...
```
Everything is working on my local machine.

**Comment by sonicaj** [comment]
Thank you @titou386 for clarifying :)

**Pull request merged**
