### PR TITLE
Update to Jellyfin plugin

### PR DESCRIPTION
**Pull request by spz2k9**
This is to update the plugin to install the packages from the official repo instead of downloading the package with a script.

### CODE REVIEW

**Review by sonicaj — APPROVED** [review]
Thank you @spz2k9 for your contribution! 
Before we merge this, can you confirm please if the artifact repo has been updated as well so that it does not pull that in via a script ?

**Comment by spz2k9** [comment]
Yes the update script has been removed and it does pull from a command in the post install IE (pkg install -y ffmpeg jellyfin libva-intel-media-driver)... but once merge i'll be able to remove jellyfin... and libva-intel-media-driver (i think it gets pulled for ffmpeg).

**Comment by spz2k9** [comment]
Oh, never mind... I've just rechecked the jellyfin.json and it already pull libva-intel-media-driver so I'll be able to remove the command entirely.

**Comment by sonicaj** [comment]
@spz2k9 can you please confirm when this should be ready for merging ? Thanks!

**Comment by spz2k9** [comment]
@sonicaj, Yes it's ready.

**Comment by spz2k9** [comment]
Pull request applied on my side : https://github.com/spz2k9/iocage-plugin-jellyfin/pull/6

**Pull request merged**
