### PR TITLE
[UPDATE][MovieNight] Add package

### PR DESCRIPTION
**Pull request by zorglube**
Thank you for your submission to the FreeNAS community plugins repository!

Please ensure the following guidelines are met when submitting a new Plugin.

1. Add the entry to INDEX in alphabetical order <= Check 
2. Includes a new icon in the ./icon/ directory <= Check 
3. Ensure the submitted icon file is a valid PNG that is 128x128 in size <= Check 
4. Add new plugin cirrus task <= Check 

I'm waiting until this PR validation to merge the [plugin deployment update](https://github.com/zorglube/iocage-plugin-movienight/pull/4)

### CODE REVIEW

**Comment by fulder** [comment]
@zorglube, this repository nowadays contains some plugin installation checks, but the PR merging them in for the first time missed the `movienight` plugin (it was merged in parallel with the test PR :cry:) hence my other PR enabling the tests for e.g. the `movienight` plugin here: https://github.com/ix-plugin-hub/iocage-plugin-index/pull/182.

As it hasn't been merged yet, could you maybe cherry-pick this commit: https://github.com/ix-plugin-hub/iocage-plugin-index/pull/182/commits/45c3965a7f0b04ffab601fa18230583b5850b554 alternatively add the tests for this plugin as well? :)

**Comment by zorglube** [comment]
I'm not sure I get correctly what you want from me. You want me to `cherry-pick` [this commit 45c3965](https://github.com/ix-plugin-hub/iocage-plugin-index/commit/45c3965a7f0b04ffab601fa18230583b5850b554) into my [master branche](https://github.com/zorglube/iocage-plugin-index/tree/maste) before merging this PR  ?

**Comment by zorglube** [comment]
@fulder just back ported the changes.

**Comment by fulder** [comment]
>I'm not sure I get correctly what you want from me. You want me to cherry-pick this commit 45c3965 into my master branche before merging this PR ?

Yes, exactly, if it wasn't too problematic.

>@fulder just back ported the changes.

Thank you! Looking green and good :smiley:

**Review by fulder — APPROVED** [review]

**Comment by sonicaj** [comment]
@zorglube can you please resolve the conflicts ? Thank you

**Comment by zorglube** [comment]
Done.

**Review by sonicaj — APPROVED** [review]

**Comment by zorglube** [comment]
@sonicaj do you have any clue about the delay before the merge to the branche 12.2-RELEASE ?

**Pull request merged**
