### PR TITLE
update to Piwigo 13

### PR DESCRIPTION
**Pull request by AfroUSApl**
Update to Piwigo 13 and fix some issues with web UI, caused by missing modules in PHP.

Thank you for your submission to the FreeNAS community plugins repository!

Please ensure the following guidelines are met when submitting a new Plugin.

1. Add the entry to INDEX in alphabetical order
2. Includes a new icon in the ./icon/ directory
3. Ensure the submitted icon file is a valid PNG that is 128x128 in size
4. Add new plugin cirrus task

### CODE REVIEW

**Comment by AfroUSApl** [comment]
May I ask how to include version of plugin in TrueNAS please, at the moment it says Version: N/A

**Comment by AfroUSApl** [comment]
Hello, still waiting to get approval for this update, I have still old version installed via TrueNAS plugin page.

**Comment by jasker5183** [comment]
Been doing some testing and Piwigo works with php74 and php80 (with some rough patches) although it looks like php74 is going eol here at the end of November (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261604). So I don't know how much sense it makes to replace php80 with php74?

**Comment by AfroUSApl** [comment]
> ...Piwigo works with php74 and php80 (with some rough patches) 

What patches did you use please?

**Comment by jasker5183** [comment]
> > ...Piwigo works with php74 and php80 (with some rough patches)
> 
> What patches did you use please?

I just meant there were some rough patches, as in after you click "begin installation" it still goes to a blank white screen but it still installs correctly and works. I did not actually apply any software patching.

**Pull request closed without merging**
