### PR TITLE
Refactor install script

### PR DESCRIPTION
**Pull request by fulder**
Test script refactor mainly splitting up the test code into small functions. I'm hoping this will make the code more readable. The results seem to match the current master state, so hopefully (:crossed_fingers:) I haven't broken anything with this refactor: https://cirrus-ci.com/build/4672974751006720.

(I.e. no new test install functionality is added here)

### CODE REVIEW

**Comment by fulder** [comment]
Thank you for merging https://github.com/ix-plugin-hub/iocage-plugin-index/pull/197 into master @sonicaj. I have synced master into this branch and solved the conflicts after this. So this one should be ready for review/merge as well :smiley_cat:

**Comment by tprelog** [comment]
BTW -- Thank you for the continued work to improve this :smile:

**Comment by fulder** [comment]
@tprelog No problem, happy to help and hopefully improve the plugin development experience and auto-feedback. I'm starting to feel satisfied with the current install script (but any improvement suggestions in text/chat/PRs are always welcome) so hope this script will get in a more stable state after this without moving much more.

**Comment by fulder** [comment]
The test run in this repo/PR seems to match current master state as well. Feel free to review/merge this (ping @sonicaj :angel:).

**Review by sonicaj — APPROVED** [review]
Thank you @fulder for your contribution as always ;)

**Pull request merged**
