### PR TITLE
Change git to git-lite for bazarr plugin

### PR DESCRIPTION
**Pull request by fulder**
Minor package change for `bazarr` plugin from `git` to `git-lite`. It is only used for a `git clone` command inside the `post_install` script so should speed up a fresh install a bit.

### CODE REVIEW

**Comment by fulder** [comment]
Install tests is still green so I'm happy. Feel free to review/merge this :)

**Comment by sonicaj** [comment]
@fulder can you please resolve the conflict ? Thanks

**Review by kmoore134 — APPROVED** [review]

**Comment by fulder** [comment]
Should be resolved and ready now again.

**Review by sonicaj — APPROVED** [review]
Thanks!

**Pull request merged**
