### PR TITLE
Update Community Plugins to 13.1-RELEASE

### LINKED ISSUE #316: Update Community Plugin's to 13.1-RELEASE
Now that TrueNAS CORE U1 is out and we are running proper 13.1 can we please upgrade our jails?

Thanks.

### PR DESCRIPTION
**Pull request by jasker5183**
Changed release to 13.1.

Fixes #316

### CODE REVIEW

**Comment by jasker5183** [comment]
The plugin's that still fail:

* bazarr - admin portal
* deluge-pip - no py39-libtorrent-rasterbar package in repo
* emby
* emby-server-stable
* esphome - artifact intervention required as script set's it to python 3.8
* gitlab
* heimdall-dashboard - missing php80 (hash, json, and openssl) packages in repo
* hoobs - node-18 is installed but not npm-18?
* n8n - admin portal
* nexus
* nzbget
* openspeedtest-server
* openvpn - no logs does not specify why it fails
* piwigo - php80 (hash and json) not found in repo
* rtorrent-flood
* sickchill - admin portal
* torr_server

The unificontroller and zabbixserver were also updated in a way I'm not sure if there will be problems, maybe their databases will handle it?

For some of these I'm wondering if the missing packages can be omitted from the .json? For others artifact intervention is going to be required and I do not have the time to file an issue for each, so should I just reset the .json back to original and it can be fixed at a later date?

**Comment by tprelog** [comment]
> * esphome - artifact intervention required as script set's it to python 3.8

ESPHome should be removed - Maybe you can cherry-pick this commit from master

- https://github.com/ix-plugin-hub/iocage-plugin-index/pull/313

**Comment by jasker5183** [comment]
Disabled Cirrus tests for the following plugin's as they were taking an hour each:

* adguardhome - passes
* calibre-web - passes
* channels-dvr - passes
* gitea - passes
* gitlab - fails
* grafana - passes
* greylog - passes
* jenkins-lts - passes
* logitechmediaserver - passes
* motioneye - passes

**Comment by jasker5183** [comment]
After this recent bout of tests nxfilter now seems to fail, not being able to find it's admin portal.

**Comment by jasker5183** [comment]
The following plugins will not start:

* emby
* emby-server-stable
* nzbget
* rtorrent-flood (Manged to get npm installed but service still won't start so test fails, might be [this](https://github.com/pierrickrouxel/iocage-plugin-rtorrent-flood/issues/10))

The following plugins are having test issues with their admin portals leaving to to believe that they work but the test fails, time allowing I will test some of these:

* bazarr
* n8n
* nxfilter
* openspeedtest-server
* piwigo
* sickchill

The following are probably going to need artifact intervention:

* deluge-pip (Broken python bindings, explained [here](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265004).  There is also [this](https://github.com/jsegaert/iocage-plugin-deluge-pip/issues/10) issue leading me to believe that 12-U8.1 doesn't even have python38 any longer. Could just leave this as is and when py39-libtorrent-rasterbar finally makes it into the repo it should work.)
* gitlab
* nexus-oss
* openvpn (Test fails with no log.)
* torr_server

**Comment by jasker5183** [comment]
These plugin's are working even though their tests are failing:

* bazarr
* n8n

### Emby/emby-server-stable

At some point Emby has switched from Mono to .NET so the service file that used to start it will no longer work. You can replace it with this one ([emby-server.txt](https://github.com/ix-plugin-hub/iocage-plugin-index/files/9294869/emby-server.txt)). Or just do a `pkg delete -a` and `pkg install emby-server` and `service emby-server start`. Going to have to file an issue with the artifact to get this one fixed.

### Nxfilter

This plugin is broken it doesn't work, the script in its artifact doesn't even download the program. If you go to the website and fetch the file to the `/usr/local/nxfilter` folder and unzip it then chmod +x the scripts in the bin folder, then restart the service it should work after that. With the broken scripts you won't get updates either, another issue to be filed with it's authors artifact.

### openspeedtest-server

This installs with `403 forbidden` on the admin portal page, I'm guessing this is a permission issue of some kind but I was unable to figure out what the problem was. One of the only plugins I'm considering rolling back to the 12.3-RELEASE.

### Piwigo

No idea what's going on with this one the admin portal just shows a white screen, couldn't find anything in the logs to figure out what was going on. Which is somewhat better than the 12.3 version where is just completely fails to install because of php73. 

### Sickchill

Must be missing a dependency in the .json because if you `pip install sickchill` and restart the service it will run fine, I'm not too sure what it's missing though.

Still need to check the following:

* nexus-oss
* nzbget
* openvpn
* rtorrent-flood
* torr_server

**Comment by jasker5183** [comment]
That should be it. If you accept this merge request the only plugin that should break (that isn't already broken) would be openspeedtest-server (which maybe should be left back on the 12.3-RELEASE) but I'll leave that decision up to someone else.

**Comment by jasker5183** [comment]
Had to add allow_mlock to sonarr.json, also had to file an issue on the FreeBSD bugzilla [here](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265801) as Sonarr is not in the 13 Latest repo.

**Review by sonicaj — COMMENTED** [review]
Thank you @jasker5183 for your contribution. I have one concern, why have we not rebased from master and then later fixed any other issues which might have come separately ?

**Comment by jasker5183** [comment]
I have no idea how to answer that question I just cloned the repo and started working on the 13.1 branch, master is a mess. Shouldn't the 13.1 branch have been rebased off master?

**Comment by tprelog** [comment]
It is confusing right now. Considering plugins were switched from `12.2-RELEASE` to `12.3-RELEASE` in both of the release branches but that change never went through master either. So it would seem there were going to be commits to resolve no matter which direction we go.

**Comment by sonicaj** [comment]
@jasker5183 i am closing this PR in favour of https://github.com/ix-plugin-hub/iocage-plugin-index/pull/324 and https://github.com/ix-plugin-hub/iocage-plugin-index/pull/323.

Right now, I am going to make sure that master -> 13.1-RELEASE mirror each other and future changes would first go to master and then a clean/neat rebase to 13.1-RELEASE would be good and we would not face conflicts that way.

Thank you @jasker5183 for your contribution, it's much appreciated!

**Comment by sonicaj** [comment]
Please do have a peek at #324 and let me know if something looks off. The changes should ideally be the exact same as you proposed apart from cleaning up the git part. Thanks!

**Pull request closed without merging**
