### PR TITLE
Update channels-dvr to use 12.2-RELEASE

### PR DESCRIPTION
**Pull request by tmm1**
Simple bump to 12.2-RELEASE

### CODE REVIEW

**Comment by fulder** [comment]
We have some new automated tests for plugin installation in this repo now :) Could you bump the version inside the `.cirrus.yml` for this plugin as well?

**Comment by tmm1** [comment]
Done

**Comment by fulder** [comment]
> Done

Thank you! Looks like there is some errors with the installation check. I'm guessing the plugin packages need an update as well (https://cirrus-ci.com/task/5061771565203456?command=install#L280)

**Comment by tmm1** [comment]
Which package repo is used?

In the past there were issues but it was fixed with a repo switch? https://github.com/ix-plugin-hub/iocage-plugin-index/pull/98#issuecomment-659801555

**Comment by tmm1** [comment]
Looks like the json has it:

>    "packagesite": "http://pkg.FreeBSD.org/${ABI}/latest",

So I wonder why www/chromium is missing there?

**Comment by tmm1** [comment]
@fulder the test is passing now!

Do I need to backport this to other branches so users on latest TrueNAS stable can use it?

**Comment by fulder** [comment]
> Which package repo is used?
Looks like the json has it:
"packagesite": "http://pkg.FreeBSD.org/${ABI}/latest",

That's correct, so after the 12.2 bump in this PR this would resolve to: `http://pkg.FreeBSD.org/FreeBSD:12:amd64/latest`

>I need the chromium package and it's not available.
>So I wonder why www/chromium is missing there?

As you probably figured it out the chromium package seems to only be available in the `quarterly` packagesite (see table at: https://www.freshports.org/www/chromium). Not sure why it's missing for `FreeBSD:12:amd64` but is present for the 13/14 `latest` versions. Guess it is fine to use quarterly until it is released for the `latest` and/or we bump this to 13-14 again some time in the future. 

> @fulder the test is passing now!

Good job! Then I'm happy :smile: 

> Do I need to backport this to other branches so users on latest TrueNAS stable can use it?

In order for this change to take effect on the latest TN system it needs to be backported to the currently latest branch (`12.2-RELEASE`), yes.

**Review by fulder — APPROVED** [review]
Adding my approval :)

**Comment by tmm1** [comment]
Thank you for the help! I opened a backport PR as well. Hope these can both be merged soon.

**Review by kmoore134 — APPROVED** [review]

**Pull request merged**
